import "./globals.css";
import { Inter } from "next/font/google";
import { headers } from "next/headers";
import Providers from "./authProviders/Providers";
import { getServerSession } from "next-auth";

import { authConfig } from "../../auth";
import Navbar from "../components/ui/navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NFT Market",
  description: "Generated by create-wagmi",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authConfig);
  const headersList = headers();
  const cookie = await headersList.get("cookie");
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers session={session} cookie={cookie}>
        <Navbar />

          {children}
        </Providers>
      </body>
    </html>
  );
}
